### ISSUE TITLE
Gerber version of the board

### ISSUE THREAD

**Issue by adrianmihalko** [WingTangWong/ESP8266_Programming_D1_Mini_Pogo_Jig#1]
Somebody please can convet Eagle .brd file into Gerber project? Many PCB services are accepting only this format.

**Comment by WingTangWong** [comment]
Hey hey, resolving this issue. I've been migrating other stuff to KiCad, finally got around to this one. You can find the Gerber and Drill files in the [Production Files folder.](https://github.com/WingTangWong/ESP8266_Programming_D1_Mini_Pogo_Jig/tree/main/PRODUCTION_FILES)
